name: Continuous Integration

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: forumapi_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: ['22.13.0']

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies & Run Migrations + Test
      run: |
        npm install
        npm run migrate up
        npm test
      env:
        CI: true
        HOST: localhost
        PORT: 3000
        PGHOST: localhost
        PGPORT: 5432
        PGUSER: postgres
        PGPASSWORD: mysecretpassword
        PGDATABASE: forumapi_test

        ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
        REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
        ACCESS_TOKEN_AGE: 3600
